import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";


export const metadata: Metadata = {
  title: "Nestora",
  description: "Generated by Sumaya Islam ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-full"
    >
      <body className="">
        <Toaster position="top-right" richColors></Toaster>
        {children}
        </body>
    </html>
  );
}
